[tools]
rojo = { github = "rojo-rbx/rojo", version = "=7.4.4" }
selene = { github = "Kampfkarren/selene", version = "=0.25.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "=0.18.1" }
luau-lsp = { github = "JohnnyMorganz/luau-lsp", version = "=1.35.0" }